//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedImgDBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public long AcctID { get; set; }
        public string AcctLName { get; set; }
        public string AcctPasswd { get; set; }
        public string AcctStatus { get; set; }
        public System.DateTime AcctCreateTime { get; set; }
    
        public virtual user user { get; set; }
    }
}
