//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedImgDBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public image()
        {
            this.comments = new HashSet<comment>();
            this.reports = new HashSet<report>();
            this.ImgPath = "images/";
            this.ImgCreateTime = DateTime.UtcNow;
            this.ImgStatus = 1;
            this.RepStatus = 1;
        }
        [DisplayName("Image ID")]
        public long ImgID { get; set; }
        [DisplayName("Image Path")]
        public string ImgPath { get; set; }
        [DisplayName("Image Name")]
        public string ImgName { get; set; }
        [DisplayName("Create Time")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public System.DateTime ImgCreateTime { get; set; }
        [DisplayName("Image Creator")]
        public long ImgCreator { get; set; }
        [DisplayName("Expert")]
        public Nullable<long> ImgExpID { get; set; }
        [DisplayName("Doctor")]
        public Nullable<long> ImgDocID { get; set; }
        [DisplayName("Patient")]
        public long ImgPatID { get; set; }
        public long ImgStatus { get; set; }
        public long RepStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
        public virtual imagestatu imagestatu { get; set; }
        public virtual patient patient { get; set; }
        public virtual reportstatu reportstatu { get; set; }
        public virtual user Createuser { get; set; }
        public virtual user Docuser { get; set; }
        public virtual user Expuser { get; set; }
    }
}
