//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedImgDBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public image()
        {
            this.comments = new HashSet<comment>();
            this.reports = new HashSet<report>();
        }
    
        public long ImgID { get; set; }
        public string ImgPath { get; set; }
        public string ImgName { get; set; }
        public System.DateTime ImgCreateTime { get; set; }
        public long ImgCreator { get; set; }
        public Nullable<long> ImgExpID { get; set; }
        public Nullable<long> ImgDocID { get; set; }
        public long ImgPatID { get; set; }
        public long StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
        public virtual patient patient { get; set; }
        public virtual imagestatu imagestatu { get; set; }
        public virtual user Createuser { get; set; }
        public virtual user Docuser { get; set; }
        public virtual user Expuser { get; set; }
    }
}
