//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedImgDBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public long RepID { get; set; }
        public string RepPath { get; set; }
        public string RepText { get; set; }
        public System.DateTime RepCreateTime { get; set; }
        public long RepCreator { get; set; }
        public long ImgID { get; set; }
    
        public virtual image image { get; set; }
        public virtual user user { get; set; }
    }
}
